### ISSUE TITLE
Support storage uri in "mongodb+srv://" format

### ISSUE THREAD

**Issue by lrhtony** [alisaifee/limits#101]
I want to use DNS Seed List Connection Format to connect MongoDB，  but it throws an exception
```
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\flask_limiter\extension.py", line 294, in __init__
    self.init_app(app)
  File "D:\Python\Python38\lib\site-packages\flask_limiter\extension.py", line 332, in init_app
    storage_from_string(
  File "D:\Python\Python38\lib\site-packages\limits\storage\__init__.py", line 60, in storage_from_string
    raise ConfigurationError("unknown storage scheme : %s" % storage_string)
limits.errors.ConfigurationError: unknown storage scheme : mongodb+srv://example.com/?retryWrites=true&w=majority
```
Here is the documentation about this format.
https://docs.mongodb.com/manual/reference/connection-string/#dns-seed-list-connection-format
This format is supported in pymongo 3.6 and later

**Comment by alisaifee** [comment]
I wasn't able to actually test the change to support this - but I've pushed a dot release - if you could give `2.3.3` a try - it should work ([2.3.3 Changelog](https://limits.readthedocs.io/en/stable/changelog.html#v2-3-3))

**Comment by lrhtony** [comment]
It works in my application
Thanks
