### ISSUE TITLE
How to limit based on token?

### ISSUE THREAD

**Issue by alexjolig** [alisaifee/limits#122]
Hi, how can I implement rate limit based on user id or token? I couldn't find the code where it checks IP to replace it with token.

**Comment by alisaifee** [comment]
What you limit by is not implemented in this library - it is left for the downstream client (for example `Flask-Limiter`).
You can see some examples in the [quickstart](https://limits.readthedocs.io/en/stable/quickstart.html#consume-the-limits) where consuming a limit ([RateLimiter.hit](https://limits.readthedocs.io/en/stable/api.html#limits.strategies.RateLimiter.hit)) takes any number of `identifiers` which are combined to form the key to limit by.

**Comment by alisaifee** [comment]
Yeap! that's right.
