### ISSUE TITLE
Plans to add support for DynamoDB

### ISSUE THREAD

**Issue by JWLee89** [alisaifee/limits#157]
Hi, 

I was just wondering if there are any plans in the future to add support for DynamoDB. 

Thank you in advance

**Comment by alisaifee** [comment]
There are no plans to add DynamoDB support but happy to consider it - though I don't have any experience with it myself.

**Comment by alisaifee** [comment]
@JWLee89 I took a quick look at the DynamoDB api and I don't see a straightforward approach for supporting both fixed & moving window. If you're interested in contributing support for DynamoDB I'm happy to take a look!

**Comment by JWLee89** [comment]
> @JWLee89 I took a quick look at the DynamoDB api and I don't see a straightforward approach for supporting both fixed & moving window. If you're interested in contributing support for DynamoDB I'm happy to take a look!

Thank you for taking a look at this issue. I just wanted to enquire if there was any plans to add support for DynamoDB. 
Writing a maintainable implementation, while playing well with the existing structure might seem like a challenge. 

> If you're interested in contributing support for DynamoDB I'm happy to take a look!

In the future, I might take a look at limits source code and take on this challenge. 

Thank you for taking time to look into this issue. I will close it for now.
