### ISSUE TITLE
`pkg_resources` is deprecated

### ISSUE THREAD

**Issue by Garrett-R** [alisaifee/limits#158]
The module `pkg_resources` gets imported [here](https://github.com/alisaifee/limits/blob/master/limits/util.py#L11), but that package is deprecated.  From [the docs](https://setuptools.pypa.io/en/latest/pkg_resources.html):

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) and their backports

Specifically, while using the [Flask-Limiter](https://github.com/alisaifee/flask-limiter) package (which uses this package), I get this stack trace:
```python
api/app.py:5: in <module>
    from flask_limiter import Limiter
../../.virtualenvs/redacted/lib/python3.11/site-packages/flask_limiter/__init__.py:4: in <module>
    from .errors import RateLimitExceeded
../../.virtualenvs/redacted/lib/python3.11/site-packages/flask_limiter/errors.py:7: in <module>
    from .wrappers import Limit
../../.virtualenvs/redacted/lib/python3.11/site-packages/flask_limiter/wrappers.py:10: in <module>
    from limits import RateLimitItem, parse_many
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/__init__.py:5: in <module>
    from . import _version, aio, storage, strategies
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/aio/__init__.py:1: in <module>
    from . import storage, strategies
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/aio/storage/__init__.py:6: in <module>
    from .base import MovingWindowSupport, Storage
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/aio/storage/base.py:5: in <module>
    from limits.storage.registry import StorageRegistry
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/storage/__init__.py:12: in <module>
    from .base import MovingWindowSupport, Storage
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/storage/base.py:6: in <module>
    from limits.util import LazyDependency
../../.virtualenvs/redacted/lib/python3.11/site-packages/limits/util.py:11: in <module>
    import pkg_resources
../../.virtualenvs/redacted/lib/python3.11/site-packages/pkg_resources/__init__.py:121: in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
```

**Comment by Garrett-R** [comment]
Oh, you made Flask-Limiter too!  Nice package, thanks for that!

**Comment by alisaifee** [comment]
Thanks for the reminder! I'm guessing you're running with `PYTHONWARNINGS=error`? 
Considering enabling that in the CI to catch these earlier.

The fix will be available soon. Unfortunately this requires reeling in the `importlib_resources` backport since the necessary implementation to load resources from subdirectories only exists in the stdlib with python 3.9+ and limits supports 3.8+.

**Comment by Garrett-R** [comment]
> I'm guessing you're running with PYTHONWARNINGS=error?

Yup, basically!  I have in my `pyproject.toml`:

```toml
[tool.pytest.ini_options]
filterwarnings = ["error"]
```

> the necessary implementation to load resources from subdirectories only exists in the stdlib with python 3.9+ and limits supports 3.8+

Bummer!  Would be nice if you could just drop 3.8 support, but I guess people on it will appreciate the support.  You know, you could also just do this:
```python
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=DeprecationWarning)
    # As soon as we drop Python 3.8 support, we can easily update this since the 
    # necessary implementation to load resources from subdirectories only exists 
    # in the stdlib with python 3.9+
    import pkg_resources 
```

**Comment by alisaifee** [comment]
Thanks for the tip! I didn't know about `warnings.catch_warnings`. Having said that, adding the dependency to `importlib_resources` is reasonable imo and the fix is now available in [3.3.0](https://github.com/alisaifee/limits/releases/tag/3.3.0)

**Comment by Garrett-R** [comment]
Oh nice!! Wow, thanks for the fast fix!

**Comment by alisaifee** [comment]
No worries, though looks like I spoke to soon and the release hadn't been ... released. It is now though.

**Comment by Garrett-R** [comment]
Cool, thanks!

**Comment by alisaifee** [comment]
@Garrett-R please close the issue once you've had a chance to verify it!

**Comment by Garrett-R** [comment]
I actually interface with this lib through `Flask-Limiter`, will there be a release there too?

**Comment by alisaifee** [comment]
No need, as long as you update to `limits` the error should go away!

**Comment by Garrett-R** [comment]
True!  Ok, verified it's now fixed, so closing this off.

Thanks!!
