### ISSUE TITLE
Shared ratelimit across multiple instances

### ISSUE THREAD

**Issue by devamin** [alisaifee/limits#159]
I am using https://github.com/laurents/slowapi which uses limits, I would like to know how to enforce ratelimit across instances, I found out that Redis keys are different for same request called from different instances which breaks the sharing.

**Comment by alisaifee** [comment]
Hi @devamin - the actual key used for the request will be coming from `slowapi`. limits itself will just take what gets passed in as `identifiers` [here](https://github.com/alisaifee/limits/blob/master/limits/strategies.py#L20) and concatenate them with the rate limit representation.
