### ISSUE TITLE
change coredis to redis-py

### ISSUE THREAD

**Issue by NiuBlibing** [alisaifee/limits#163]
coredis need  high version redis which not work on redis 5.

**Comment by alisaifee** [comment]
- redis 5 is already end of life and is not supported by the library anymore ([reference](https://limits.readthedocs.io/en/stable/storage.html)). 
- coredis can be made to work with redis ~ 5 by using `protocol_version=2` ([coredis compatibility documentation](https://coredis.readthedocs.io/en/latest/#compatibility)).
