### ISSUE TITLE
Support redis cluster like aws Elasti Cache

### ISSUE THREAD

**Issue by surreal-xiyichan** [alisaifee/limits#172]
I found can't no support Elasti Cache.

**Comment by alisaifee** [comment]
Redis cluster is supported, some details [here](https://limits.readthedocs.io/en/stable/storage.html#redis-cluster-storage).

**Comment by surreal-xiyichan** [comment]
> Redis cluster is supported, some details [here](https://limits.readthedocs.io/en/stable/storage.html#redis-cluster-storage).

thanks
