### ISSUE TITLE
Unnecessary dependency on setuptools

### ISSUE THREAD

**Issue by SpecLad** [alisaifee/limits#175]
## Expected Behaviour

limits should not declare a dependency on setuptools, as it hasn't needed it since 9cb7716.

## Current Behaviour

It does: https://github.com/alisaifee/limits/blob/9a98ac20f63224faeb1875e0506c75c0b62215ab/requirements/main.txt#L3

## Your Environment

- limits version: 3.5.0

**Comment by alisaifee** [comment]
Thanks! Fixed in f19ef6ee29d204c1465359a400f75e36d6aa191d and will be available in the next release.
