### ISSUE TITLE
Pass options to Redis.from_url() in RedisStorage

### ISSUE THREAD

**Issue by tuukkamustonen** [alisaifee/limits#18]
https://github.com/alisaifee/limits/blob/master/limits/storage.py#L364 ignores passed kwargs (options) while it could just pass them along to `Redis.from_url()` in https://github.com/alisaifee/limits/blob/master/limits/storage.py#L372.

At the moment, redis 2.10.5 is not parsing query strings correctly (see https://github.com/andymccurdy/redis-py/pull/723 for fix) so it's not possible to configure `socket_timeout` and `socket_connect_timeout` and such.

Fix for URL query string parsing will be included in 2.10.6 but it shouldn't hurt to just pass the options along here, either?

**Comment by gruentee** [comment]
This would be really great, as we could use sockets!

**Comment by alisaifee** [comment]
This has been resolved as of v1.4
