### ISSUE TITLE
Make limits more flexible specifically in conjunction with flask_limiter

### ISSUE THREAD

**Issue by reallistic** [alisaifee/limits#2]
It would be awesome to have the following options in limits that can be passed to it via other packages (such as flask_limiter).

 - Specify the use of [bmemcached](https://github.com/jaysonsantos/python-binary-memcached) for saslmemcached connections or regular memcached connections.
 - Allow configuration options specific to storage providers. For example setting a redis key prefix or telling pymemcache what socket module to use.

(Feature requests originated in pull #1)

**Comment by alisaifee** [comment]
@rxsegrxup I've made a few minor (undocumented) changes both in limits & flask-limiter which are along the lines of this request. Basically you can pass extra kwargs to the storage constructors now. The memcached storage class accepts a string `library` and callable `client_getter` which are used to construct the memcache client internally. `client_getter` should accept two arguments, 1) the instance of the library and 2) a list of the (host,port) tuples. The setting can be sent through Flask-Limiter as well by settings the `RATELIMIT_STORAGE_OPTIONS` configuration value up as a dictionary.
