### ISSUE TITLE
How do you block until the rate has capacity?

### ISSUE THREAD

**Issue by iainelder** [alisaifee/limits#221]
Came here from [Justin Van Winkle's survey of Python rate limiters](https://gist.github.com/justinvanwinkle/d9f04950083c4554835c1a35f9d22dad). He said limits "seems to work", which is high praise because the rest were somehow broken.

Am I missing something with the `hit` function?

[Quickstart](https://limits.readthedocs.io/en/stable/quickstart.html) shows how to assert whether it returns `True` or `False` and to sleep to make a previous `False` turn `True`.

```python
assert True == moving_window.hit(one_per_minute, "test_namespace", "foo")
assert False == moving_window.hit(one_per_minute, "test_namespace", "foo")
assert True == moving_window.hit(one_per_minute, "test_namespace", "bar")

assert True == moving_window.hit(one_per_second, "test_namespace", "foo")
assert False == moving_window.hit(one_per_second, "test_namespace", "foo")
time.sleep(1)
assert True == moving_window.hit(one_per_second, "test_namespace", "foo")
```

I want a rate limiter that blocks until the request would satisfy the limit; that is, as soon as `hit` would return `True`.

I suppose I could built something like that using `hit`, but I don't want to. If I have to start writing sleeps into my code, then I think there's something missing from my rate limiter library.

**Comment by iainelder** [comment]
The [Check without consuming](https://limits.readthedocs.io/en/stable/quickstart.html#check-without-consuming) example gave me a clue.

I need to add this pattern into any function that I want to be rate-limited.

```python
while not await moving_window.test(one_per_minute, "test_namespace"):
        time.sleep(0.01)
assert await moving_window.hit(one_per_minute, "test_namespace")
```

Is that how you expect me to use this? If so, I would make a PR that clarifies this in the docs.

Better still would be a decorator (or indications on how to build one) so I don't have to add this inside my functions.

**Comment by alisaifee** [comment]
Although this is for the async context, #237 is one way to achieve this without repeatedly hitting the backend.

**Comment by iainelder** [comment]
@alisaifee , thanks for the response.

I'm not currently using the library.

I'll accept your response as a solution, and if the question comes up again, I or someone else can open a new issue.
