### ISSUE TITLE
Memcache storage multiple host support

### ISSUE THREAD

**Issue by verterok** [alisaifee/limits#25]
Hi,

I'm starting to test flask-limiter in one of our services and while testing it found that limits MemcacheStorage doesn't support multiple hosts by default. Check https://github.com/alisaifee/limits/blob/master/limits/storage.py#L610, get_client uses module.Client(*hosts) and by default module is pymemcache.client which only supports a single host.

Maybe the docs should be fixed to point out that a single memcached host is supported unless a custom client_getter is provided? 

P.S: workaround this with a custom client_getter to use pymemcache.client.hash.HashClient instead, but now hitting a different issue with flask-limiter.

**Comment by verterok** [comment]
Found the cause of the issue making flask-limiter not behave as it should. Sadly, it's because of how limits handle the noreply keyword argument and how pymemcache HashClient methods are defined. 

In https://github.com/alisaifee/limits/blob/master/limits/storage.py#L619 where inspect.getargspec(func).args is used to check if noreply is supported in the client function. And if you take a look at HashClient, all the client methods use variable length arguments, e.g: https://github.com/pinterest/pymemcache/blob/master/pymemcache/client/hash.py#L316

**Comment by alisaifee** [comment]
This has been resolved as of v1.5 where you don't need a custom client getter and if the number of hosts specified is > 1 then a hashclient will be used by default.
