### ISSUE TITLE
[Contribution question] Handling storage#incr returning None

### ISSUE THREAD

**Issue by jkirsteins** [alisaifee/limits#27]
Hi,

I have a situation, where memcached storage#incr sometimes returns None. This is not handled in FixedWindowRateLimiter at the moment (it raises `TypeError: unorderable types: NoneType() <= int()` in FixedWindowRateLimiter#hit.

Would a PR be accepted, where FixedWindowRateLimiter#hit returns False, if storage#incr returns None?

**Comment by alisaifee** [comment]
This is probably too little too late, but I've verified that the cases where `incr` was returning None have now bee handled
