### ISSUE TITLE
Threading based lock will not work on multi-machine system

### ISSUE THREAD

**Issue by twolfson** [alisaifee/limits#3]
While reviewing `limits`/`flask-limiter`, we came across a scaling issue that we wanted to bring up. The current Redis implementation is using a non-Redis based mechanism for locking. Instead, it is using a threading based lock.

https://github.com/alisaifee/limits/blob/1.0.6/limits/storage.py#L55-L56

https://github.com/alisaifee/limits/blob/1.0.6/limits/storage.py#L249

https://github.com/alisaifee/limits/blob/1.0.6/limits/storage.py#L279

This is fine for when a service is running on 1 machine but when it goes to multiple machines with multiple disks, then it falls apart. Instead of this approach, maybe move to dynamic Redis keys that leverage `INCR` instead to avoid the locking issue altogether? (e.g. `127.0.0.1/endpoint/epoch_000`, `127.0.0.1/endpoint/epoch_100`)

**Comment by alisaifee** [comment]
Hi @twolfson https://github.com/alisaifee/limits/blob/1.0.6/limits/storage.py#L249 refers to https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py#L9 which uses redis for its locking.

**Comment by twolfson** [comment]
Ah, sorry. I must have gotten my thoughts confused. Thanks for clarifying.

**Comment by twolfson** [comment]
On a tangent from this, is the locking mechanism required? In case of a denial of service attack, then that would require requests to be held open longer which is more likely to take the service down due to running out of connections.

**Comment by alisaifee** [comment]
The lock is only used in the moving window implementation and isn't *strictly* required as in the worst case only one extra request would get through. At the very least I think a reasonably small timeout when trying to acquire the lock could help. Failure to acquire the lock within the timeout could result in the rate limit being marked as 'hit' as a client is bursting at a rate high enough to hit a lock is probably not up to any good. What do you think?

**Comment by twolfson** [comment]
I think both options have their benefits. It most likely boils down to whether the developer wants to be as performant as possible or as accurate as possible.

Marking the lock acquisition as a failure might be interesting. How would it work with a non-responsive Redis instance? In those cases, it might be better to 500 rather than 429.

**Comment by alisaifee** [comment]
@twolfson: I've added a lock timeout in b6b755d2a5a25a7a2fbf986428b4bae023cd7c35
If the lock can't be acquired it will raise a `LockError` which when used with `Flask-Limiter` will currently result in a `500` error.  I'll further add new options in `Flask-Limiter` to configure what to do when an error is encountered when attempting to rate limit a route.
