### ISSUE TITLE
Add support for async backend clients

### ISSUE THREAD

**Issue by laurentS** [alisaifee/limits#60]
In order to make [slowapi](https://github.com/laurentS/slowapi/issues/3) asyncio compatible, I would need to update the layers underneath to work asynchronously. I think the key part is getting `limits` to support asyncio.

Would you be interested in me having a go at it? I think it would be possible to either:
- add a few `async def` methods on the strategies, something like `RateLimiter.ahit()` and `RateLimiter.atest()`
- Create `AsyncRateLimiter` and subclasses.

And then add an async storage backend, starting with `redis`.

Otherwise, if you see no interest in having this in the same code base, I guess I could fork the library and do more or less the same, but I think it's probably more valuable to have everything together.

**Comment by alisaifee** [comment]
This is now available in a pre-release (2.1.0bN) and contains support for redis, memcached & mongodb.
The support is limited to python 3.7, 3.8 & 3.9 as both the redis & memcached dependencies are not installable / functional on python 3.10 yet.

I'll soon be making a 2.1.0 release which contains these features - but you can take them for a ride already by installing for example:
```
pip install limits[async-redis]==2.1.0b3
```
