### ISSUE TITLE
Create a RedisSentinelStorage via an already existing sentinel instance

### ISSUE THREAD

**Issue by thestick613** [alisaifee/limits#7]
Your implementation supports sentinel but it doesn't support authentication. I already had a sentinel instance initialized in my code, which i used for multiple purposes, so will you accept a PR which allows creating this?
thx

**Comment by alisaifee** [comment]
I've made a tweak in master (220ce8ceeb2e1848a4917e711bfc2b17a5c9dd83) so that the url scheme for `RedisSentinelStorage` is now at parity with `RedisStorage` - allowing you to pass authentication parameters through the url for example `redis+sentinel://:foobared@localhost:26379/my-service`

If however, you still want a way to reuse an existing sentinel instance I would recommend going the subclass route:

```
from limits.storage import RedisSentinelStorage
from redis.sentinel import Sentinel

sentinel = Sentinel([("localhost", 26379)], password="foobared")
assert True == sentinel.master_for("localhost-redis-sentinel").ping()

class CustomSentinelStorage(RedisSentinelStorage):
    STORAGE_SCHEME = "customsentinel"
    def __init__(self, sentinel, service_name):
        self.service_name = service_name
        self.sentinel = sentinel

storage = CustomSentinelStorage(sentinel, "localhost-redis-sentinel") 
assert True == storage.check()
```

**Comment by thestick613** [comment]
This is i am actually using in production. It works perfectly, though i don't understand why you skip the 
`initialize_storage` and the `__init__`:

    class RedisSentinelStorageViaInstance(RedisSentinelStorage):
        STORAGE_SCHEME = "redis+sentinel"

        def __init__(self, sentinel_instance, service_name):
            self.sentinel = sentinel_instance
            self.service_name = service_name
            self.initialize_storage()
            super(RedisSentinelStorage, self).__init__()

**Comment by alisaifee** [comment]
Thats neat - you're calling the `__init__` of the `super` of the `super`.
Skipping the `initialize_storage` call was a mistake.
