### ISSUE TITLE
Type hints & PEP 561 packaging

### ISSUE THREAD

**Issue by tuukkamustonen** [alisaifee/limits#72]
Add type hints to all (at least public API) code make the distribution PEP 561 compliant. This allows `mypy` (and other tools?) to find the type hints and use them in linting.

In practice, add an empty `limits/py.typed` file, and include it in the package:

```py
setup(
    package_data={'limits': ['py.typed']},
    zip_safe=False,  # not needed with wheels, AFAIK
)
```

PEP 561: https://www.python.org/dev/peps/pep-0561/

**Comment by alisaifee** [comment]
This is now available in the 2.x releases.
