### ISSUE TITLE
Is it possible to use a Redis connection pool?

### ISSUE THREAD

**Issue by pieroliviermarquis** [alisaifee/limits#77]
Connecting to a connection pool would be very useful. I have an issue with my application reaching the maximum number of Redis clients.

**Comment by VeNoMouS** [comment]
Well the problem comes when your using flask / gunicorn for example under green threads.. gunicorn isnt going to share the connection / connection pool because of the green thread...

So each thread is going to open up its own connection pool and when you have a cluster of servers it really hits the redis... when you doing thousands of requests a second 

you can can put nutcracker on the local system as a "middleware" to use just one connection from the server itself to the redis server , but due to the exact queries your code is running, it isnt supported in nutcracker

**Comment by alisaifee** [comment]
I think you might be able to use redis-proxy in envoy (which supports lua scripting afaik) [reference](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis)

**Comment by VeNoMouS** [comment]
> When you say connection pool, do you mean being able to do something like this:
> 
> ```
> from limits.storage import RedisStorage
> from limits.strategies import MovingWindowRateLimiter
> import redis
> pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
> storage = RedisStorage(connection_pool = pool)
> limiter = MovingWindowRateLimiter(storage)
> ```
> 
> Unfortunately not at the moment - since the redis implementation delegates the construction of the redis client entirely to the `redis.Redis.from_url` function.
> 
> Having said it does seem reasonable to reuse a shared connection pool in your application and there have been other use-cases where letting the application provide a "Storage" that has been pre-constructed.

HI @alsaifee,

just circling back around to this, to see if this would be possible ?  as if you using gunicorn etc, using a redis BlockingConnectionPool and monkey patching gevent can limit the number / rape connections being opened

**Comment by VeNoMouS** [comment]
could https://github.com/alisaifee/limits/blob/b22ccbbde73b12941891c8e8c534c602f78eca05/limits/storage/redis.py#L126-L129

be replaced with something along like the follwoing...

```python
    redis = self.dependencies["redis"]
    if isinstance(uri, redis.client.Redis):
        self.storage = uri
    else:
        uri = uri.replace("redis+unix", "unix")
        self.storage = redis.from_url(uri, **options)
```

**Comment by alisaifee** [comment]
@VeNoMouS could you take a look at #110 to see if that'll work for you?

**Comment by VeNoMouS** [comment]
Will test today for you

**Comment by alisaifee** [comment]
You shouldn't need to hack anything in flask-limiter, this should work:

```
from flask_limiter import Limiter
pool = ....
limiter = Limiter(....., storage_uri="redis://", storage_options={"connection_pool": pool})
```

**Comment by VeNoMouS** [comment]
> You shouldn't need to hack anything in flask-limiter, this should work:
> 
> ```
> from flask_limiter import Limiter
> pool = ....
> limiter = Limiter(....., storage_uri="redis://", storage_options={"connection_pool": pool})
> ```

ok cheers will test out in a bit and let you know

**Comment by alisaifee** [comment]
:bow:

**Comment by VeNoMouS** [comment]
Since my stuff is in a docker... this is a dirty trick to pull the code base with the PR incase you didnt know...

```
https://api.github.com/repos/alisaifee/limits/zipball/pull/110/head```

**Comment by VeNoMouS** [comment]
Appears to be working @alisaifee

**Comment by VeNoMouS** [comment]
Testing it now on a test production server

**Comment by alisaifee** [comment]
I've cut a `2.4.0` release if you want to give that a shot as well!

**Comment by VeNoMouS** [comment]
Sure , give me ~hour and ill roll out another test

**Comment by VeNoMouS** [comment]
2.4.0 appears to be working

**Comment by alisaifee** [comment]
Awesome! Thanks for helping verify and also the idea!

**Comment by VeNoMouS** [comment]
thanks for patching ❤️
