### ISSUE TITLE
"TypeError: object bool can't be used in 'await' expression" with MemoryStorage in Async

### ISSUE THREAD

**Issue by zoltan-fedor** [alisaifee/limits#99]
Hi @alisaifee ,

Sorry, it is me again. Apologies for sending yet another issue.

I might have found another bug in the async module, this time with the MemoryStorage.
I took my `redis+sentinel` async example and turned it into a `MemoryStorage` one and I got an error.

This same code runs fine if I replace the line with the store to be the one from `Redis`, but fails with the `MemoryStorage`:
```
import asyncio
from limits import parse
from limits.storage import storage_from_string, MemoryStorage
from limits.aio.strategies import MovingWindowRateLimiter

# store = storage_from_string("async+redis://:xxxx@localhost:63796")  # with this line it runs fine
store = MemoryStorage()   # with this line it fails

moving_window = MovingWindowRateLimiter(store)
one_per_minute = parse("1/minute")

async def hit():
   return await moving_window.hit(one_per_minute, "test_namespace", "foo")

loop = asyncio.get_event_loop()
loop.run_until_complete(hit())
loop.close()
```

Error:
```
Traceback (most recent call last):
  File "test-async-limits.py", line 18, in <module>
    loop.run_until_complete(hit())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test-async-limits.py", line 15, in hit
    return await moving_window.hit(one_per_minute, "test_namespace", "foo")
  File "/home/user/.local/share/virtualenvs/test-limits-kWUTuU1U/lib/python3.8/site-packages/limits/aio/strategies.py", line 85, in hit
    return await self.storage().acquire_entry(  # type: ignore
TypeError: object bool can't be used in 'await' expression
```

**Comment by alisaifee** [comment]
No problem! I'm happy to see the async storages get some testing! 
In this case it's not exactly a bug but more of a documentation issue:

```
import asyncio
from limits import parse
from limits.storage import storage_from_string
from limits.aio.storage import MemoryStorage # memory storage has a separate aio implementation

from limits.aio.strategies import MovingWindowRateLimiter

store = MemoryStorage()   
# or 
store = storage_from_string("async+memory://")
```

I thought it would be better to have just one `storage_from_string` but perhaps that creates some confusion. One potential solution is to raise an exception if an async strategy is initialized with a sync storage....

**Comment by zoltan-fedor** [comment]
Thanks, that makes perfect sense!

I am okey with just one `storage_from_string`, but yes, I can see a scenario where people might forget to add the `async+` to the URI string and still trying to use the limits in async. At some point that might necessitate the addition of an exception to remind them of that.

Yes, I am prepping a release for Falcon-Limiter which would include async, that's why suddenly I am bringing all these questions. :-)
